### ISSUE TITLE
Create a pipeline to deploy the master branch to the cloud

### ISSUE THREAD

**Issue by ambid17** [oneleif/olWebsite#47]
We would like an easy way to run tests and deploy the project to the cloud once Vapor Cloud is no longer available. We are planning to use Circle CI, and our hosting platform is HostGator.

**Comment by arkus7** [comment]
Do we have VPS on HostGator or just web hosting?

If it's VPS we could make a CircleCI workflow to test, build and then send the built binary to the HostGator server (using `scp` or `rsync`) and restart it. It shouldn't be very difficult.

**Comment by 0xLeif** [comment]
HostGator is our DNS provider currently. Vapor.cloud is our hosting platform. The two main platforms Vapor suggests are AWS and Heroku.

https://docs.vapor.cloud/shutdown/
