### ISSUE TITLE
Research the best cloud deployment platform

### ISSUE THREAD

**Issue by ambid17** [oneleif/olWebsite#48]

**Comment by arkus7** [comment]
It depends on if we looking for something free for non-profits.

According to the discussion in [this issue](https://github.com/oneleif/olWebsite/issues/47), I was trying to find something about Heroku and AWS.

Heroku is really easy to set up I think. They don't have any discounts or free services for non-profit organizations though.

https://help.heroku.com/VF2KIQ5S/does-heroku-offer-non-profit-or-educational-discounts

I would say that AWS requires more initial setup (depends on how much we want to automate deployments, do we want to have two environments of the app like stage and prod) but also gives you more flexibility I guess. Not sure about the discounts for non-profit.

I found [this](https://aws.amazon.com/government-education/nonprofits/) but the **AWS Credit Program for Nonprofits** seems like $2,000 of credits valid for a year for the price of $175.

They have the free tier for 1 year. If you haven't used it yet, this might be a good start. There are 750 hours of EC2 per month in the free tier which covers a whole month, so we'll probably end up with one server instance working.

What do you think about this @zmeriksen @ambid17 ?

**Comment by ambid17** [comment]
I think you're right, I would like to choose AWS. Even if it is more work up front, it's what the industry uses and will give everyone more experience.

**Comment by 0xLeif** [comment]
I think that we should use AWS... It seems like it is the most popular for the industry

**Comment by arkus7** [comment]
I have only a little experience with DevOps stuff (most of the work is done by external company in my job), but I'm happy to learn, so I could try to set things up.

Question is what about multiple environments. Should we use AWS only for production env and others like stage have on a different (free) provider like Heroku or maybe we should try to squeeze other environments on the same server e.g. in other Docker container and provided on different domains (e.g. stage.oneleif.com).

For the frontend, we could use AWS S3 with CloudFront.

**Comment by arkus7** [comment]
I found one more option, Google Cloud Run. It is super easy to set up (just tried with my uni project). All you have to do is dockerize your application and make it listen on `PORT` env variable.

I posted this also on Discord: https://alexolivier.me/posts/deploy-container-stateless-cheap-google-cloud-run-serverless

There should be similar to AWS one year free tier with $300 to spend on GCloud services (at least I got it, valid for 12 months).
Here you can find pricing: https://cloud.google.com/run/pricing
Seems like the pricing is per request, not per instance running time, so the quiet days won't be included in the billings.

@ambid17 @zmeriksen 

Also, the domain was really easy to setup (just verification by adding some TXT/CNAME records) and then adding additional CNAME record and you have your project running on your custom domain.

**Comment by 0xLeif** [comment]
@arkus7 I'm still leaning towards AWS...

[Google likes to kill things...](https://killedbygoogle.com)

**Comment by arkus7** [comment]
We went with AWS. I think we can close this @ambid17?
